#!/usr/bin/env python3
"""Generate a source-focused codebase scan from tracked repository files."""

from __future__ import annotations

import argparse
import subprocess
from collections import Counter
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "docs" / "codebase" / ".codebase-scan.txt"

IGNORED_GENERATED_PREFIXES = (
    ".agents/",
    ".execution_artifacts/",
    "client_submission/",
    "frontend/dist/",
    "frontend/build/",
    "frontend/playwright-report/",
    "frontend/test-results/",
    "frontend/node_modules/",
    "backend/execution_runtime/node_modules/",
    "backend/execution_runtime/artifacts/",
    "node_modules/",
)

IGNORED_GENERATED_PARTS = {
    "__pycache__",
    ".pytest_cache",
    ".ruff_cache",
}

TEXT_SUFFIXES = {
    ".css",
    ".env",
    ".example",
    ".gitignore",
    ".html",
    ".js",
    ".json",
    ".jsx",
    ".md",
    ".py",
    ".sh",
    ".toml",
    ".txt",
    ".yml",
    ".yaml",
}


@dataclass(frozen=True)
class FileStat:
    path: str
    size_bytes: int
    line_count: int


def run_git_ls_files(root: Path) -> list[str]:
    result = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=root,
        check=True,
        capture_output=True,
        text=False,
    )
    return [item.decode("utf-8") for item in result.stdout.split(b"\0") if item]


def is_ignored_generated_path(path: str) -> bool:
    normalized = path.replace("\\", "/")
    if any(normalized == prefix.rstrip("/") or normalized.startswith(prefix) for prefix in IGNORED_GENERATED_PREFIXES):
        return True
    return any(part in IGNORED_GENERATED_PARTS for part in normalized.split("/"))


def source_paths(paths: list[str]) -> list[str]:
    return sorted(path for path in paths if not is_ignored_generated_path(path))


def is_probably_text(path: Path) -> bool:
    if path.suffix.lower() in TEXT_SUFFIXES:
        return True
    try:
        sample = path.read_bytes()[:4096]
    except OSError:
        return False
    return b"\0" not in sample


def line_count(path: Path) -> int:
    if not is_probably_text(path):
        return 0
    try:
        return len(path.read_text(encoding="utf-8", errors="replace").splitlines())
    except OSError:
        return 0


def collect_file_stats(root: Path, paths: list[str]) -> list[FileStat]:
    stats: list[FileStat] = []
    for relative_path in paths:
        full_path = root / relative_path
        try:
            size_bytes = full_path.stat().st_size
        except OSError:
            continue
        stats.append(FileStat(path=relative_path, size_bytes=size_bytes, line_count=line_count(full_path)))
    return stats


def extension_label(path: str) -> str:
    suffix = Path(path).suffix.lower()
    if suffix:
        return suffix
    return "[no extension]"


def top_level_label(path: str) -> str:
    return path.split("/", 1)[0]


def format_table(rows: list[tuple[str, int]], label_header: str, value_header: str) -> list[str]:
    lines = [f"| {label_header} | {value_header} |", "| --- | ---: |"]
    lines.extend(f"| `{label}` | {value} |" for label, value in rows)
    return lines


def build_report(root: Path, raw_paths: list[str]) -> str:
    paths = source_paths(raw_paths)
    excluded_count = len(raw_paths) - len(paths)
    stats = collect_file_stats(root, paths)
    total_bytes = sum(item.size_bytes for item in stats)
    total_lines = sum(item.line_count for item in stats)
    top_by_size = sorted(stats, key=lambda item: item.size_bytes, reverse=True)[:20]
    extension_counts = Counter(extension_label(item.path) for item in stats)
    directory_counts = Counter(top_level_label(item.path) for item in stats)

    lines = [
        "# Codebase Scan",
        "",
        "Generated by `python scripts/scan_codebase.py`.",
        "",
        "Scope: tracked repository files after explicit generated/local-output exclusions.",
        "",
        "## Summary",
        "",
        f"- Files scanned: {len(stats)}",
        f"- Files excluded after `git ls-files`: {excluded_count}",
        f"- Total bytes: {total_bytes}",
        f"- Text lines counted: {total_lines}",
        "",
        "## Excluded Ignored Generated/Local Prefixes",
        "",
    ]
    lines.extend(f"- `{prefix}`" for prefix in IGNORED_GENERATED_PREFIXES)
    lines.extend(f"- path part `{part}`" for part in sorted(IGNORED_GENERATED_PARTS))
    lines.extend(
        [
            "",
            "## Top-Level Directories",
            "",
            *format_table(directory_counts.most_common(), "Directory", "Files"),
            "",
            "## Extensions",
            "",
            *format_table(extension_counts.most_common(), "Extension", "Files"),
            "",
            "## Largest Tracked Files",
            "",
            "| Path | Bytes | Lines |",
            "| --- | ---: | ---: |",
        ]
    )
    lines.extend(f"| `{item.path}` | {item.size_bytes} | {item.line_count} |" for item in top_by_size)
    lines.append("")
    return "\n".join(lines)


def write_report(output_path: Path, report: str) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(report, encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate a tracked-source codebase scan.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Path to write the scan output.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    raw_paths = run_git_ls_files(ROOT)
    write_report(args.output, build_report(ROOT, raw_paths))
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
